-- V1__create_iespflix_schema.sql
-- Schema do banco do IESPFLIX

CREATE TABLE IF NOT EXISTS usuarios (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo    VARCHAR(150) NOT NULL,
    data_nascimento  DATE         NOT NULL,
    email            VARCHAR(254) NOT NULL UNIQUE,
    senha_hash       VARCHAR(60)  NOT NULL,
    cpf_cnpj         VARCHAR(14)  UNIQUE,
    perfil           VARCHAR(20)  NOT NULL DEFAULT 'USER'
);

CREATE TABLE IF NOT EXISTS conteudo (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo           VARCHAR(200)  NOT NULL,
    tipo             VARCHAR(10)   NOT NULL,
    ano              SMALLINT      NOT NULL,
    duracao_minutos  SMALLINT      NOT NULL,
    relevancia       DECIMAL(4,2)  NOT NULL,
    sinopse          TEXT,
    trailer_url      VARCHAR(500),
    genero           VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS plano (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo         VARCHAR(20)   NOT NULL UNIQUE,
    limite_diario  SMALLINT      NOT NULL,
    preco          DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS assinatura (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT      NOT NULL,
    plano_id     BIGINT      NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'ATIVA',
    iniciada_em  TIMESTAMP   NOT NULL,
    cancelada_em TIMESTAMP,
    CONSTRAINT fk_assinatura_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_assinatura_plano   FOREIGN KEY (plano_id)   REFERENCES plano(id)
);

CREATE TABLE IF NOT EXISTS metodo_pagamento (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT       NOT NULL,
    bandeira       VARCHAR(20)  NOT NULL,
    ultimos4       CHAR(4)      NOT NULL,
    mes_exp        SMALLINT     NOT NULL,
    ano_exp        SMALLINT     NOT NULL,
    nome_portador  VARCHAR(150) NOT NULL,
    token_gateway  VARCHAR(120) NOT NULL,
    CONSTRAINT fk_metodo_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- dados iniciais de planos
INSERT INTO plano (codigo, limite_diario, preco) VALUES
    ('BASICO',   1,  19.90),
    ('PADRAO',   3,  34.90),
    ('PREMIUM', 999, 49.90);

-- conteúdos de exemplo
INSERT INTO conteudo (titulo, tipo, ano, duracao_minutos, relevancia, sinopse, trailer_url, genero) VALUES
    ('Interestelar',  'FILME', 2014, 169, 9.5, 'Uma equipe viaja além da galáxia em busca de um novo lar.', 'https://youtu.be/zSWdZVtXT7E', 'Ficção Científica'),
    ('Breaking Bad',  'SERIE', 2008,  47, 9.9, 'Um professor de química se torna produtor de drogas.',      'https://youtu.be/HhesaQXLuRY', 'Crime'),
    ('Coringa',       'FILME', 2019, 122, 8.5, 'A origem do vilão mais famoso dos quadrinhos.',              'https://youtu.be/zAGVQLHvwOY', 'Drama'),
    ('Dark',          'SERIE', 2017,  60, 9.3, 'Quatro famílias investigam um desaparecimento em 1986.',     'https://youtu.be/rrwycJ08PSA', 'Ficção Científica'),
    ('Clube da Luta', 'FILME', 1999, 139, 9.2, 'Um homem insatisfeito forma um clube de luta secreto.',      NULL,                           'Drama');
